/*******************************************************************************************
*  This class is autogenerated from the class ConsoleLogger.cs
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;

namespace CodeEffect.Diagnostics.EventSourceGenerator
{
	internal sealed class ConsoleLogger : ConsoleApplication1.IConsoleLogger
	{
		private int _processId;

		public ConsoleLogger(
			int processId)
		{
			_processId = processId;
		}

		public void SayGoodbye(
			string goodbye, 
			DateTime nightTime)
		{

			sample.Current.SayGoodbye(
				_processId, 
				goodbye, 
				nightTime
			);
		}


	}
}
