/*******************************************************************************************
*  This class is autogenerated from the class ConsoleRunnerLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Collections.Generic;
using ConsoleApplication1.Loggers;


namespace ConsoleApplication1
{
	internal sealed class ConsoleRunnerLogger : IConsoleRunnerLogger
	{
	    private sealed class ScopeWrapper : IDisposable
        {
            private readonly IEnumerable<IDisposable> _disposables;

            public ScopeWrapper(IEnumerable<IDisposable> disposables)
            {
                _disposables = disposables;
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            private void Dispose(bool disposing)
            {
                if (disposing)
                {
                    foreach (var disposable in _disposables)
                    {
                        disposable.Dispose();
                    }
                }
            }
        }

	    private sealed class ScopeWrapperWithAction : IDisposable
        {
            private readonly Action _onStop;

            internal static IDisposable Wrap(Func<IDisposable> wrap)
            {
                return wrap();
            }

            public ScopeWrapperWithAction(Action onStop)
            {
                _onStop = onStop;
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            private void Dispose(bool disposing)
            {
                if (disposing)
                {
                    _onStop?.Invoke();
                }
            }
        }


		private readonly bool _autogenerated;
		private readonly string _machineName;

		public ConsoleRunnerLogger(
			bool autogenerated,
			string machineName)
		{
			_autogenerated = autogenerated;
			_machineName = machineName;
		}

		public void RunnerCreated(
			)
		{
			ConsoleApplication1EventSource.Current.RunnerCreated(
				_autogenerated, 
				_machineName
			);
    
		}


		public void RunnerDestroyed(
			)
		{
			ConsoleApplication1EventSource.Current.RunnerDestroyed(
				_autogenerated, 
				_machineName
			);
    
		}


		public void WaitingForKeyPress(
			)
		{
			ConsoleApplication1EventSource.Current.WaitingForKeyPress(
				_autogenerated, 
				_machineName
			);
    
		}


		public void KeyPressed(
			System.ConsoleKey key)
		{
			ConsoleApplication1EventSource.Current.KeyPressed(
				_autogenerated, 
				_machineName, 
				key
			);
    
		}


		public void UnsupportedKeyError(
			System.Exception ex)
		{
			ConsoleApplication1EventSource.Current.UnsupportedKeyError(
				_autogenerated, 
				_machineName, 
				ex
			);
    
		}


		public void StartLoop(
			)
		{
			ConsoleApplication1EventSource.Current.StartLoop(
				_autogenerated, 
				_machineName
			);
    
		}


		public void StopLoop(
			)
		{
			ConsoleApplication1EventSource.Current.StopLoop(
				_autogenerated, 
				_machineName
			);
    
		}


		public void RandomIntsGenerated(
			int[] values)
		{
			ConsoleApplication1EventSource.Current.RandomIntsGenerated(
				_autogenerated, 
				_machineName, 
				values
			);
    
		}


	}
}
