/*******************************************************************************************
*  This class is autogenerated from the class DependencyLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Collections.Generic;
using ConsoleApplication1.Loggers;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;
using System.Runtime.Remoting.Messaging;


namespace ConsoleApplication1
{
	internal sealed class DependencyLogger : IDependencyLogger
	{
	    private sealed class ScopeWrapper : IDisposable
        {
            private readonly IEnumerable<IDisposable> _disposables;

            public ScopeWrapper(IEnumerable<IDisposable> disposables)
            {
                _disposables = disposables;
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            private void Dispose(bool disposing)
            {
                if (disposing)
                {
                    foreach (var disposable in _disposables)
                    {
                        disposable.Dispose();
                    }
                }
            }
        }

	    private sealed class ScopeWrapperWithAction : IDisposable
        {
            private readonly Action _onStop;

            internal static IDisposable Wrap(Func<IDisposable> wrap)
            {
                return wrap();
            }

            public ScopeWrapperWithAction(Action onStop)
            {
                _onStop = onStop;
            }

            public void Dispose()
            {
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            private void Dispose(bool disposing)
            {
                if (disposing)
                {
                    _onStop?.Invoke();
                }
            }
        }


		private readonly bool _autogenerated;
		private readonly string _machineName;
		private readonly Microsoft.ApplicationInsights.TelemetryClient _telemetryClient;

        public sealed class OperationHolder
        {
            public static void StartOperation(IOperationHolder<RequestTelemetry> aiOperationHolder)
            {
                OperationHolder.Current = new OperationHolder() {AIOperationHolder = aiOperationHolder};
            }

            public static IOperationHolder<RequestTelemetry> StopOperation()
            {
                var aiOperationHolder = OperationHolder.Current.AIOperationHolder;
                OperationHolder.Current = null;

                return aiOperationHolder;
            }

            private IOperationHolder<RequestTelemetry> AIOperationHolder { get; set; }

            private static readonly string ContextKey = Guid.NewGuid().ToString();

            public static OperationHolder Current
            {
                get { return (OperationHolder)CallContext.LogicalGetData(ContextKey); }
                internal set
                {
                    if (value == null)
                    {
                        CallContext.FreeNamedDataSlot(ContextKey);
                    }
                    else
                    {
                        CallContext.LogicalSetData(ContextKey, value);
                    }
                }
            }
        }

		public DependencyLogger(
			bool autogenerated,
			string machineName)
		{
			_autogenerated = autogenerated;
			_machineName = machineName;
			
            _telemetryClient = new Microsoft.ApplicationInsights.TelemetryClient();
            _telemetryClient.Context.User.Id = Environment.UserName;
            _telemetryClient.Context.Session.Id = Guid.NewGuid().ToString();
            _telemetryClient.Context.Device.OperatingSystem = Environment.OSVersion.ToString();

		}


        public System.IDisposable CallExternalComponent(
			System.Uri requestName,
			string content)
		{
		    return new ScopeWrapper(new IDisposable[]
		    {

                ScopeWrapperWithAction.Wrap(() =>
		        {
			ConsoleApplication1EventSource.Current.StartCallExternalComponent(
				_autogenerated, 
				_machineName, 
				requestName, 
				content
			);
    
		            return new ScopeWrapperWithAction(() =>
		            {
			ConsoleApplication1EventSource.Current.StopCallExternalComponent(
				_autogenerated, 
				_machineName, 
				requestName, 
				content
			);
    
		            });
		        }),


                ScopeWrapperWithAction.Wrap(() =>
		        {

			            var callExternalComponentOperationHolder = _telemetryClient.StartOperation<DependencyTelemetry>(requestName.ToString() ?? "callExternalComponent");
			            callExternalComponentOperationHolder.Telemetry.Properties.Add("Autogenerated", _autogenerated.ToString());
			callExternalComponentOperationHolder.Telemetry.Properties.Add("MachineName", Environment.MachineName);
			callExternalComponentOperationHolder.Telemetry.Properties.Add("RequestName", requestName.ToString());
			callExternalComponentOperationHolder.Telemetry.Properties.Add("Content", content);
    
		            return new ScopeWrapperWithAction(() =>
		            {

			            _telemetryClient.StopOperation<DependencyTelemetry>(callExternalComponentOperationHolder);
    
		            });
		        }),


		    });
		}






        public System.IDisposable RecieveMessage(
			string message)
		{
		    return new ScopeWrapper(new IDisposable[]
		    {

                ScopeWrapperWithAction.Wrap(() =>
		        {
			ConsoleApplication1EventSource.Current.StartRecieveMessage(
				_autogenerated, 
				_machineName, 
				message
			);
    
		            return new ScopeWrapperWithAction(() =>
		            {
			ConsoleApplication1EventSource.Current.StopRecieveMessage(
				_autogenerated, 
				_machineName, 
				message
			);
    
		            });
		        }),


                ScopeWrapperWithAction.Wrap(() =>
		        {

			            var recieveMessageOperationHolder = _telemetryClient.StartOperation<RequestTelemetry>("recieveMessage");
			            recieveMessageOperationHolder.Telemetry.Properties.Add("Autogenerated", _autogenerated.ToString());
			recieveMessageOperationHolder.Telemetry.Properties.Add("MachineName", Environment.MachineName);
			recieveMessageOperationHolder.Telemetry.Properties.Add("Message", message);
    
		            return new ScopeWrapperWithAction(() =>
		            {

			            _telemetryClient.StopOperation<RequestTelemetry>(recieveMessageOperationHolder);
    
		            });
		        }),


		    });
		}





	}
}
