/*******************************************************************************************
*  This class is autogenerated from the class ServiceHostLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace WebApiService
{
	internal sealed partial class WebApiServiceEventSource
	{

		private const int ServiceTypeRegisteredEventId = 401;

		[Event(ServiceTypeRegisteredEventId, Level = EventLevel.LogAlways, Message = "Service Type Registered {0} {1}", Keywords = Keywords.ServiceHost)]
		public void ServiceTypeRegistered(
			int processId, 
			string serviceTypeName)
		{
			WriteEvent(
				ServiceTypeRegisteredEventId, 
				processId, 
				serviceTypeName);
		}


		private const int ServiceHostInitializationFailedEventId = 802;

		[Event(ServiceHostInitializationFailedEventId, Level = EventLevel.LogAlways, Message = "{0}", Keywords = Keywords.ServiceHost)]
		private void ServiceHostInitializationFailed(
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				ServiceHostInitializationFailedEventId, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void ServiceHostInitializationFailed(
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				ServiceHostInitializationFailed(
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.AsJson());
			}
		}


	}
}