/*******************************************************************************************
*  This class is autogenerated from the class WebApiLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using WebApiService.Diagnostics;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;
using CodeEffect.Diagnostics.EventSourceGenerator.AI;


namespace WebApiService
{
	internal sealed class WebApiLogger : IWebApiLogger
	{
		private readonly System.Fabric.StatelessServiceContext _context;
		private readonly Microsoft.ApplicationInsights.TelemetryClient _telemetryClient;

		public WebApiLogger(
			System.Fabric.StatelessServiceContext context)
		{
			_context = context;
			
            _telemetryClient = new Microsoft.ApplicationInsights.TelemetryClient();
            _telemetryClient.Context.User.Id = Environment.UserName;
            _telemetryClient.Context.Session.Id = Guid.NewGuid().ToString();
            _telemetryClient.Context.Device.OperatingSystem = Environment.OSVersion.ToString();

		}

		public void ActivatingController(
			)
		{
			WebApiServiceEventSource.Current.ActivatingController(
				_context
			);
			_telemetryClient.TrackEvent(
	            nameof(ActivatingController),
	            new System.Collections.Generic.Dictionary<string, string>()
	            {
	                {"ServiceName", _context.ServiceName.ToString()},
                    {"ServiceTypeName", _context.ServiceTypeName},
                    {"ReplicaOrInstanceId", _context.InstanceId.ToString()},
                    {"PartitionId", _context.PartitionId.ToString()},
                    {"ApplicationName", _context.CodePackageActivationContext.ApplicationName},
                    {"ApplicationTypeName", _context.CodePackageActivationContext.ApplicationTypeName},
                    {"NodeName", _context.NodeContext.NodeName}
	            });
    
		}



		public void StartGetAll(
			)
		{
			WebApiServiceEventSource.Current.StartGetAll(
				_context
			);

			var getAllOperationHolder = _telemetryClient.StartOperation<RequestTelemetry>("getAll");
	       getAllOperationHolder.Telemetry.Properties.Add("ServiceName", _context.ServiceName.ToString());
			getAllOperationHolder.Telemetry.Properties.Add("ServiceTypeName", _context.ServiceTypeName);
			getAllOperationHolder.Telemetry.Properties.Add("ReplicaOrInstanceId", _context.InstanceId.ToString());
			getAllOperationHolder.Telemetry.Properties.Add("PartitionId", _context.PartitionId.ToString());
			getAllOperationHolder.Telemetry.Properties.Add("ApplicationName", _context.CodePackageActivationContext.ApplicationName);
			getAllOperationHolder.Telemetry.Properties.Add("ApplicationTypeName", _context.CodePackageActivationContext.ApplicationTypeName);
			getAllOperationHolder.Telemetry.Properties.Add("NodeName", _context.NodeContext.NodeName);
	       OperationHolder.StartOperation(getAllOperationHolder);
    
		}



		public void StopGetAll(
			)
		{
			WebApiServiceEventSource.Current.StopGetAll(
				_context
			);
	        var getAllOperationHolder = OperationHolder.StopOperation();
			_telemetryClient.StopOperation(getAllOperationHolder);
			getAllOperationHolder.Dispose();
    
		}



	}
}
