/*******************************************************************************************
*  This class is autogenerated from the class PersonActorServiceLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using PersonActor.Diagnostics;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;
using CodeEffect.Diagnostics.EventSourceGenerator.AI;


namespace PersonActor
{
	internal sealed class PersonActorServiceLogger : IPersonActorServiceLogger
	{
		private readonly Microsoft.ServiceFabric.Actors.Runtime.ActorService _actorService;
		private readonly CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext _context;
		private readonly Microsoft.ApplicationInsights.TelemetryClient _telemetryClient;

		public PersonActorServiceLogger(
			Microsoft.ServiceFabric.Actors.Runtime.ActorService actorService,
			CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext context)
		{
			_actorService = actorService;
			_context = context;
			
            _telemetryClient = new Microsoft.ApplicationInsights.TelemetryClient();
            _telemetryClient.Context.User.Id = Environment.UserName;
            _telemetryClient.Context.Session.Id = Guid.NewGuid().ToString();
            _telemetryClient.Context.Device.OperatingSystem = Environment.OSVersion.ToString();

		}

		public void PersonGenerated(
			string name,
			string title)
		{
			PersonActorServiceEventSource.Current.PersonGenerated(
				_actorService, 
				_context, 
				name, 
				title
			);
			_telemetryClient.TrackEvent(
	            nameof(PersonGenerated),
	            new System.Collections.Generic.Dictionary<string, string>()
	            {
	                {"ActorType", _actorService.ActorTypeInformation.ImplementationType.ToString()},
                    {"ApplicationTypeName", _actorService.Context.CodePackageActivationContext.ApplicationTypeName},
                    {"ApplicationName", _actorService.Context.CodePackageActivationContext.ApplicationName},
                    {"ServiceTypeName", _actorService.Context.ServiceTypeName},
                    {"ServiceName", _actorService.Context.ServiceName.ToString()},
                    {"PartitionId", _actorService.Context.PartitionId.ToString()},
                    {"ReplicaOrInstanceId", _actorService.Context.ReplicaId.ToString()},
                    {"NodeName", _actorService.Context.NodeContext.NodeName},
                    {"CorrelationId", CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext.Current?["correlationId"]},
                    {"UserId", CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext.Current?["userId"]},
                    {"RequestId", CodeEffect.ServiceFabric.Services.Remoting.FabricTransport.ServiceRequestContext.Current?["requestId"]},
                    {"Name", name},
                    {"Title", title}
	            });
    
		}



	}
}
