using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using FG.Diagnostics.AutoLogger.Generator.Utils;
using FG.Diagnostics.AutoLogger.Model;

namespace FG.Diagnostics.AutoLogger.Generator.Builders
{
    public class ProjectBuilder : BaseCoreBuilder, IProjectBuilder
    {
        public Microsoft.Build.Evaluation.Project QuickLoadProjectReference(string projectFileReference)
        {
            Microsoft.Build.Evaluation.Project project = null;
            using (var projectFileReader = XmlReader.Create(projectFileReference))
            {
                project = new Microsoft.Build.Evaluation.Project(projectFileReader);
                LogMessage($"Loaded referenced project {projectFileReference} from XML with {project.Items.Count} items");

                return project;
            }
        }

        public void Build(Project model)
        {
            LogMessage($"Scanning project {model.ProjectFilePath} for eventsource definitions");

            model.ProjectBasePath = System.IO.Path.GetDirectoryName(model.ProjectFilePath);

            var projectItems = new List<ProjectItem>();

            if (model.ProjectFilePath == null)
            {
                LogMessage($"Could not find basePath of {model.ProjectFilePath}");
            }
            if (model.ProjectBasePath != null)
            {
                var projectName = System.IO.Path.GetFileNameWithoutExtension(model.ProjectFilePath);
                Microsoft.Build.Evaluation.Project project = null;
                using (var projectFileReader = XmlReader.Create(model.ProjectFilePath))
                {
                    project = new Microsoft.Build.Evaluation.Project(projectFileReader);
                    LogMessage($"Loaded project {model.ProjectFilePath} from XML with {project.Items.Count} items");
                }

                var hasEventSource = false;
                foreach (
                    var projectItem in project.Items.Where(item => item.EvaluatedInclude.EndsWith(@".eventsource.json", StringComparison.InvariantCultureIgnoreCase))
                )
                {
                    var rootNamespace = project.Properties.FirstOrDefault(property => property.Name.Equals("RootNamespace"))?.EvaluatedValue ?? projectName;

                    var projectItemFilePath = System.IO.Path.Combine(model.ProjectBasePath, projectItem.EvaluatedInclude);
                    projectItems.Add(new ProjectItem<EventSourceModel>(ProjectItemType.EventSourceDefinition, projectItemFilePath)
                    {
                        Include = projectItem.EvaluatedInclude,
                        RootNamespace = rootNamespace
                    });
                    hasEventSource = true;
                }

                var platformProperty = project.Properties.FirstOrDefault(p => p.Name == "PlatformTarget")?.EvaluatedValue ?? "AnyCPU";
                model.Platform = platformProperty;

                foreach (var projectItem in project.Items.Where(item =>
                    item.EvaluatedInclude.Matches(@"*.eventsource.output.json", StringComparison.InvariantCultureIgnoreCase, useWildcards: true)
                    && item.ItemType == "Content"))
                {
                    var projectItemFilePath = System.IO.Path.Combine(model.ProjectBasePath, projectItem.EvaluatedInclude);                                        
                    projectItems.Add(new ProjectItem<ProjectSummary>(ProjectItemType.ProjectSummary, projectItemFilePath)
                    {
                        Include = projectItem.EvaluatedInclude,
                    });
                }

                var autogeneratedMetadataTypes = new[]
                    {
                        ProjectItemType.ProjectSummary,
                        ProjectItemType.DefaultGeneratedEventSourceDefinition,
                        ProjectItemType.EventSource,
                        ProjectItemType.EventSourceLoggerPartial,
                        ProjectItemType.LoggerImplementation
                    }
                    .Select(metadata => Enum.GetName(typeof(ProjectItemType), metadata))
                    .ToArray();
                foreach (var projectItem in project.Items.Where(item =>
                    item.EvaluatedInclude.Matches(@"(^|\\)I[^\\]*Logger.cs", StringComparison.InvariantCultureIgnoreCase, useWildcards: false)
                    && item.ItemType == "Compile"
                    && !autogeneratedMetadataTypes.Contains((item.HasMetadata("AutoGenerated") ? item.GetMetadataValue("AutoGenerated") : "") ?? "")))
                {
                    var projectItemFilePath = System.IO.Path.Combine(model.ProjectBasePath, projectItem.EvaluatedInclude);
                    projectItems.Add(new ProjectItem<LoggerTemplateModel>(ProjectItemType.LoggerInterface, projectItemFilePath) {Include = projectItem.EvaluatedInclude});
                }

                foreach (var projectItem in project.Items.Where(item =>
                    item.EvaluatedInclude.Matches(@"(^|\\)[^\\]*Extension.cs", StringComparison.InvariantCultureIgnoreCase, useWildcards: false)
                    && item.ItemType == "Compile"
                    && !autogeneratedMetadataTypes.Contains((item.HasMetadata("AutoGenerated") ? item.GetMetadataValue("AutoGenerated") : "") ?? "")))
                {
                    var projectItemFilePath = System.IO.Path.Combine(model.ProjectBasePath, projectItem.EvaluatedInclude);
                    projectItems.Add(new ProjectItem(ProjectItemType.BuilderExtension, projectItemFilePath) {Include = projectItem.EvaluatedInclude});
                }
                var anyHintPath = "";
                foreach (var projectItem in project.Items.Where(item => item.ItemType == "Reference"))
                {
                    var hintPath = projectItem.HasMetadata("HintPath") ? projectItem.GetMetadataValue("HintPath") : null;
                    hintPath = hintPath != null ? PathExtensions.GetAbsolutePath(model.ProjectBasePath, hintPath) : null;

                    anyHintPath = hintPath ?? anyHintPath;

                    var projectItemFilePath = hintPath == null ? $"{projectItem.EvaluatedInclude}.dll" : System.IO.Path.Combine(model.ProjectBasePath, hintPath);

                    projectItems.Add(new ProjectItem(ProjectItemType.Reference, projectItemFilePath) {Include = projectItem.EvaluatedInclude});
                }

                var outputPath =
                    project.Items.FirstOrDefault(item => item.ItemType.Equals("_OutputPathItem", StringComparison.InvariantCultureIgnoreCase))?.EvaluatedInclude;
                foreach (var projectItem in project.Items.Where(item => item.ItemType == "ProjectReference"))
                {
                    var referencedProjectPath = PathExtensions.GetAbsolutePath(model.ProjectBasePath, projectItem.EvaluatedInclude);
                    var referencedProjectName = System.IO.Path.GetFileNameWithoutExtension(projectItem.EvaluatedInclude);
                    var expectedDllName = $"{referencedProjectName}.dll";
                    var referencedProjectOutputPath = PathExtensions.GetAbsolutePath(System.IO.Path.GetDirectoryName(referencedProjectPath), outputPath);
                    var projectItemFilePath = System.IO.Path.Combine(referencedProjectOutputPath, expectedDllName);
                    if (System.IO.File.Exists(projectItemFilePath))
                    {
                        projectItems.Add(new ProjectItem(ProjectItemType.ProjectReference, projectItemFilePath) {Include = projectItem.EvaluatedInclude});
                    }
                    else
                    {
                        var referencedProject = QuickLoadProjectReference(referencedProjectPath);
                        var referencedProjectSubOutputPath =
                            referencedProject.Items.FirstOrDefault(item => item.ItemType.Equals("_OutputPathItem", StringComparison.InvariantCultureIgnoreCase))?
                                .EvaluatedInclude;
                        var referencedProjectAssemblyName =
                            referencedProject.Properties.FirstOrDefault(p => p.Name.Equals("AssemblyName", StringComparison.InvariantCultureIgnoreCase))?.EvaluatedValue;
                        expectedDllName = $"{referencedProjectAssemblyName}.dll";
                        referencedProjectOutputPath = PathExtensions.GetAbsolutePath(System.IO.Path.GetDirectoryName(referencedProjectPath), referencedProjectSubOutputPath);
                        projectItemFilePath = System.IO.Path.Combine(referencedProjectOutputPath, expectedDllName);
                        if (System.IO.File.Exists(projectItemFilePath))
                        {
                            projectItems.Add(new ProjectItem(ProjectItemType.ProjectReference, projectItemFilePath) {Include = projectItem.EvaluatedInclude});
                        }
                        else
                        {
                            LogError($"Could not find dll for project reference, ensure you have compiled {projectItemFilePath}");
                        }
                    }
                }

                if (!hasEventSource)
                {
                    var rootNamespace = project.Properties.FirstOrDefault(property => property.Name.Equals("RootNamespace"))?.EvaluatedValue ?? projectName;

                    var include = $"DefaultEventSource.eventsource.json";
                    var projectItemFilePath = System.IO.Path.Combine(model.ProjectBasePath, include);
                    projectItems.Add(new ProjectItem<EventSourceModel>(ProjectItemType.DefaultGeneratedEventSourceDefinition, projectItemFilePath)
                    {
                        Include = include,
                        RootNamespace = rootNamespace
                    });
                }
            }

            model.ProjectItems = projectItems.ToArray();
        }
    }

    

}