namespace FG.Diagnostics.AutoLogger.Generator.Templates
{
    public static class LoggerEventSourcePartialTemplate
    {
        // ReSharper disable InconsistentNaming
        public const string Variable_LOGGER_SOURCE_FILE_NAME = @"@@LOGGER_SOURCE_FILE_NAME@@";
        public const string Variable_NAMESPACE_DECLARATION = @"@@NAMESPACE_DECLARATION@@";
        public const string Variable_EVENTSOURCE_CLASS_NAME = @"@@EVENTSOURCE_CLASS_NAME@@";

        public const string Variable_EVENTSOURCE_PARTIAL_FILE_NAME = @"@@EVENTSOURCE_PARTIAL_FILE_NAME@@";
        public const string Variable_LOGGER_EVENTS_DECLARATION = @"@@LOGGER_EVENTS_DECLARATION@@";

        public const string Template_LOGGER_PARTIAL_CLASS_DECLARATION =
@"/*******************************************************************************************
*  This class is autogenerated from the class @@LOGGER_SOURCE_FILE_NAME@@
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace @@NAMESPACE_DECLARATION@@
{
	internal sealed partial class @@EVENTSOURCE_CLASS_NAME@@
	{
@@LOGGER_EVENTS_DECLARATION@@
	}
}";

        // ReSharper restore InconsistentNaming
    }
}