/*******************************************************************************************
*  This class is autogenerated from the class ConsoleLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using ConsoleApplication1.Loggers;

namespace ConsoleApplication1.Diagnostics
{
	internal sealed class ConsoleLogger : IConsoleLogger
	{
		private readonly int _processId;
		private readonly string _machineName;

		public ConsoleLogger(
			int processId,
			string machineName)
		{
			_processId = processId;
			_machineName = machineName;
		}

		public void SayHello(
			string message)
		{
			Sample.Current.SayHello(
				_processId, 
				_machineName, 
				message
			);

            System.Diagnostics.Debug.WriteLine($"[] ERR: SayHello");
           
            System.Diagnostics.Debug.WriteLine($"\t_processId:\t{_processId}");
            System.Diagnostics.Debug.WriteLine($"\tEnvironment.MachineName:\t{Environment.MachineName}");
            System.Diagnostics.Debug.WriteLine($"\tmessage:\t{message}");
    
		}


		public void Message(
			string message)
		{
			Sample.Current.Message(
				_processId, 
				_machineName, 
				message
			);

            System.Diagnostics.Debug.WriteLine($"[] ERR: Message");
           
            System.Diagnostics.Debug.WriteLine($"\t_processId:\t{_processId}");
            System.Diagnostics.Debug.WriteLine($"\tEnvironment.MachineName:\t{Environment.MachineName}");
            System.Diagnostics.Debug.WriteLine($"\tmessage:\t{message}");
    
		}


		public void Error(
			System.Exception exception)
		{
			Sample.Current.Error(
				_processId, 
				_machineName, 
				exception
			);

            System.Diagnostics.Debug.WriteLine($"[] ERR: Error");
           
            System.Diagnostics.Debug.WriteLine($"\t_processId:\t{_processId}");
            System.Diagnostics.Debug.WriteLine($"\tEnvironment.MachineName:\t{Environment.MachineName}");
            System.Diagnostics.Debug.WriteLine($"\texception.Message:\t{exception.Message}");
            System.Diagnostics.Debug.WriteLine($"\texception.Source:\t{exception.Source}");
            System.Diagnostics.Debug.WriteLine($"\texception.GetType().FullName:\t{exception.GetType().FullName}");
            System.Diagnostics.Debug.WriteLine($"\texception.AsJson():\t{exception.AsJson()}");
    
		}


		public void SayGoodbye(
			string goodbye,
			System.DateTime nightTime)
		{
			Sample.Current.SayGoodbye(
				_processId, 
				_machineName, 
				goodbye, 
				nightTime
			);

            System.Diagnostics.Debug.WriteLine($"[] ERR: SayGoodbye");
           
            System.Diagnostics.Debug.WriteLine($"\t_processId:\t{_processId}");
            System.Diagnostics.Debug.WriteLine($"\tEnvironment.MachineName:\t{Environment.MachineName}");
            System.Diagnostics.Debug.WriteLine($"\tgoodbye:\t{goodbye}");
            System.Diagnostics.Debug.WriteLine($"\tnightTime.ToString():\t{nightTime.ToString()}");
    
		}


		public void Special(
			ConsoleApplication1.Loggers.Special special)
		{
			Sample.Current.Special(
				_processId, 
				_machineName, 
				special
			);

            System.Diagnostics.Debug.WriteLine($"[] ERR: Special");
           
            System.Diagnostics.Debug.WriteLine($"\t_processId:\t{_processId}");
            System.Diagnostics.Debug.WriteLine($"\tEnvironment.MachineName:\t{Environment.MachineName}");
            System.Diagnostics.Debug.WriteLine($"\tspecial.ToString():\t{special.ToString()}");
    
		}


	}
}
