/*******************************************************************************************
*  This class is autogenerated from the class ConsoleLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using ConsoleApplication1.Diagnostics;

namespace ConsoleApplication1.Loggers
{
	internal sealed class ConsoleLogger : IConsoleLogger
	{
		private int _processId;

		public ConsoleLogger(
			int processId)
		{
			_processId = processId;
		}

		public void SayHello(
			string message)
		{
			sample.Current.SayHello(
				_processId, 
				message
			);
    
		}


		public void Message(
			string message)
		{
			sample.Current.Message(
				_processId, 
				message
			);
    
		}


		public void Error(
			System.Exception exception)
		{
			sample.Current.Error(
				_processId, 
				exception
			);
    
		}


		public void SayGoodbye(
			string goodbye,
			DateTime nightTime)
		{
			sample.Current.SayGoodbye(
				_processId, 
				goodbye, 
				nightTime
			);
    
		}


		public void Special(
			Special special)
		{
			sample.Current.Special(
				_processId, 
				special
			);
    
		}


	}
}
