/*******************************************************************************************
*  This class is autogenerated from the class DependencyLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace ConsoleApplication1.Diagnostics
{
	internal sealed partial class Sample
	{

		private const int StartCallExternalComponentEventId = 2001;

		[Event(StartCallExternalComponentEventId, Level = EventLevel.LogAlways, Message = "Start Call External Component {2} {3}", Keywords = Keywords.Dependency, Opcode = EventOpcode.Start, Task = Tasks.CallExternalComponent)]
		private void StartCallExternalComponent(
			int processId, 
			string machineName, 
			string requestName, 
			string content)
		{
			WriteEvent(
				StartCallExternalComponentEventId, 
				processId, 
				machineName, 
				requestName, 
				content);
		}

		[NonEvent]
		public void StartCallExternalComponent(
			int processId, 
			string machineName, 
			System.Uri requestName, 
			string content)
		{
			if (this.IsEnabled())
			{
				StartCallExternalComponent(
					processId, 
					Environment.MachineName, 
					requestName.ToString(), 
					content);
			}
		}


		private const int StopCallExternalComponentEventId = 4002;

		[Event(StopCallExternalComponentEventId, Level = EventLevel.LogAlways, Message = "Stop Call External Component {2} {3}", Keywords = Keywords.Dependency, Opcode = EventOpcode.Stop, Task = Tasks.CallExternalComponent)]
		private void StopCallExternalComponent(
			int processId, 
			string machineName, 
			string requestName, 
			string content)
		{
			WriteEvent(
				StopCallExternalComponentEventId, 
				processId, 
				machineName, 
				requestName, 
				content);
		}

		[NonEvent]
		public void StopCallExternalComponent(
			int processId, 
			string machineName, 
			System.Uri requestName, 
			string content)
		{
			if (this.IsEnabled())
			{
				StopCallExternalComponent(
					processId, 
					Environment.MachineName, 
					requestName.ToString(), 
					content);
			}
		}


		private const int StartRecieveMessageEventId = 6003;

		[Event(StartRecieveMessageEventId, Level = EventLevel.LogAlways, Message = "{3}", Keywords = Keywords.Dependency, Opcode = EventOpcode.Start, Task = Tasks.RecieveMessage)]
		public void StartRecieveMessage(
			int processId, 
			string machineName, 
			string requestName, 
			string message)
		{
			WriteEvent(
				StartRecieveMessageEventId, 
				processId, 
				machineName, 
				requestName, 
				message);
		}


		private const int StopRecieveMessageEventId = 8004;

		[Event(StopRecieveMessageEventId, Level = EventLevel.LogAlways, Message = "{3}", Keywords = Keywords.Dependency, Opcode = EventOpcode.Stop, Task = Tasks.RecieveMessage)]
		public void StopRecieveMessage(
			int processId, 
			string machineName, 
			string requestName, 
			string message)
		{
			WriteEvent(
				StopRecieveMessageEventId, 
				processId, 
				machineName, 
				requestName, 
				message);
		}


		private const int DoDirtyStuffEventId = 10005;

		[Event(DoDirtyStuffEventId, Level = EventLevel.LogAlways, Message = "Do Dirty Stuff", Keywords = Keywords.Dependency)]
		public void DoDirtyStuff(
			int processId, 
			string machineName, 
			string requestName)
		{
			WriteEvent(
				DoDirtyStuffEventId, 
				processId, 
				machineName, 
				requestName);
		}


	}
}