/*******************************************************************************************
*  This class is autogenerated from the class ConsoleRunnerLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace ConsoleApplication1.Diagnostics
{
	internal sealed partial class Sample
	{

		private const int RunnerCreatedEventId = 2001;

		[Event(RunnerCreatedEventId, Level = EventLevel.LogAlways, Message = "Runner Created", Keywords = Keywords.ConsoleRunner)]
		public void RunnerCreated(
			int processId, 
			string machineName)
		{
			WriteEvent(
				RunnerCreatedEventId, 
				processId, 
				machineName);
		}


		private const int RunnerDestroyedEventId = 4002;

		[Event(RunnerDestroyedEventId, Level = EventLevel.LogAlways, Message = "Runner Destroyed", Keywords = Keywords.ConsoleRunner)]
		public void RunnerDestroyed(
			int processId, 
			string machineName)
		{
			WriteEvent(
				RunnerDestroyedEventId, 
				processId, 
				machineName);
		}


		private const int WaitingForKeyPressEventId = 6003;

		[Event(WaitingForKeyPressEventId, Level = EventLevel.LogAlways, Message = "Waiting For Key Press", Keywords = Keywords.ConsoleRunner)]
		public void WaitingForKeyPress(
			int processId, 
			string machineName)
		{
			WriteEvent(
				WaitingForKeyPressEventId, 
				processId, 
				machineName);
		}


		private const int KeyPressedEventId = 8004;

		[Event(KeyPressedEventId, Level = EventLevel.LogAlways, Message = "Key Pressed {2}", Keywords = Keywords.ConsoleRunner)]
		private void KeyPressed(
			int processId, 
			string machineName, 
			string key)
		{
			WriteEvent(
				KeyPressedEventId, 
				processId, 
				machineName, 
				key);
		}

		[NonEvent]
		public void KeyPressed(
			int processId, 
			string machineName, 
			System.ConsoleKey key)
		{
			if (this.IsEnabled())
			{
				KeyPressed(
					processId, 
					Environment.MachineName, 
					key.ToString());
			}
		}


		private const int UnsupportedKeyErrorEventId = 10005;

		[Event(UnsupportedKeyErrorEventId, Level = EventLevel.LogAlways, Message = "{2}", Keywords = Keywords.ConsoleRunner | Keywords.Error)]
		private void UnsupportedKeyError(
			int processId, 
			string machineName, 
			string message, 
			string source, 
			string exceptionTypeName, 
			string exception)
		{
			WriteEvent(
				UnsupportedKeyErrorEventId, 
				processId, 
				machineName, 
				message, 
				source, 
				exceptionTypeName, 
				exception);
		}

		[NonEvent]
		public void UnsupportedKeyError(
			int processId, 
			string machineName, 
			System.Exception ex)
		{
			if (this.IsEnabled())
			{
				UnsupportedKeyError(
					processId, 
					Environment.MachineName, 
					ex.Message, 
					ex.Source, 
					ex.GetType().FullName, 
					ex.AsJson());
			}
		}


		private const int StartLoopEventId = 12006;

		[Event(StartLoopEventId, Level = EventLevel.LogAlways, Message = "Start Loop", Keywords = Keywords.ConsoleRunner, Opcode = EventOpcode.Start)]
		public void StartLoop(
			int processId, 
			string machineName)
		{
			WriteEvent(
				StartLoopEventId, 
				processId, 
				machineName);
		}


		private const int StopLoopEventId = 14007;

		[Event(StopLoopEventId, Level = EventLevel.LogAlways, Message = "Stop Loop", Keywords = Keywords.ConsoleRunner, Opcode = EventOpcode.Stop)]
		public void StopLoop(
			int processId, 
			string machineName)
		{
			WriteEvent(
				StopLoopEventId, 
				processId, 
				machineName);
		}


		private const int RandomIntsGeneratedEventId = 16008;

		[Event(RandomIntsGeneratedEventId, Level = EventLevel.LogAlways, Message = "Random Ints Generated {2}", Keywords = Keywords.ConsoleRunner)]
		private void RandomIntsGenerated(
			int processId, 
			string machineName, 
			string values)
		{
			WriteEvent(
				RandomIntsGeneratedEventId, 
				processId, 
				machineName, 
				values);
		}

		[NonEvent]
		public void RandomIntsGenerated(
			int processId, 
			string machineName, 
			int[] values)
		{
			if (this.IsEnabled())
			{
				RandomIntsGenerated(
					processId, 
					Environment.MachineName, 
					values.ToString());
			}
		}


	}
}