using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("FG.Diagnostics.AutoLogger.AI")]
[assembly: AssemblyDescription("Autogenerated Application Insights telemetry based on metadata descriptions")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Fabricators Guild")]
[assembly: AssemblyProduct("FG.Diagnostics.AutoLogger")]
[assembly: AssemblyCopyright("Copyright © Fabricators Guild 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("42202370-bac7-486b-ac92-5b247148e649")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.3.1.0")]
