/*******************************************************************************************
*  This class is autogenerated from the class C:\Code\labs\CodeEffect.Diagnostics.EventSourceGenerator\StandaloneTest\StandaloneTest\DefaultEventSource.cs
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace StandaloneTest
{
	[EventSource(Name = "DefaultEventSource")]
	internal sealed partial class DefaultEventSource : EventSource
	{
		public static readonly DefaultEventSource Current = new DefaultEventSource();

		static DefaultEventSource()
		{
			// A workaround for the problem where ETW activities do not 
			// get tracked until Tasks infrastructure is initialized.
			// This problem will be fixed in .NET Framework 4.6.2.
			Task.Run(() => { });
		}

		// Instance constructor is private to enforce singleton semantics
		private DefaultEventSource() : base() { }

		#region Keywords
		// Event keywords can be used to categorize events. 
		// Each keyword is a bit flag. A single event can be 
		// associated with multiple keywords (via EventAttribute.Keywords property).
		// Keywords must be defined as a public class named 'Keywords' 
		// inside EventSource that uses them.
		public static class Keywords
		{
			public const EventKeywords Domain = (EventKeywords)0x1L;

		}
		#endregion Keywords

		#region Events



		#endregion Events
	}


	internal static class Helpers
	{
		public static string AsJson(this System.Exception that)
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(that);
		}
	}


}