/*******************************************************************************************
*  This class is autogenerated from the class InfrastructureLogger
*  Do not directly update this class as changes will be lost on rebuild.
*******************************************************************************************/
using System;
using System.Diagnostics.Tracing;
using System.Threading.Tasks;

namespace Ce.Labs.Samples
{
	internal sealed partial class FGDiagnosticsAutoLoggerSamplesConsoleApplication1EventSource
	{

		private const int ActivatingServiceEventId = 4001;

		[Event(ActivatingServiceEventId, Level = EventLevel.LogAlways, Message = "Activating Service", Keywords = Keywords.Infrastructure)]
		public void ActivatingService(
			bool autogenerated, 
			string machineName)
		{
			WriteEvent(
				ActivatingServiceEventId, 
				autogenerated, 
				machineName);
		}


	}
}